"""Eliminar campos innecesarios de Pedido

Revision ID: 9884a4868645
Revises: cb1f37de4b21
Create Date: 2025-10-15 17:56:44.630984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9884a4868645'
down_revision = 'cb1f37de4b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('localidad')
        batch_op.drop_column('cp_usuario')
        batch_op.drop_column('direccion')
        batch_op.drop_column('ciudad')
        batch_op.drop_column('referencias')
        batch_op.drop_column('provincia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provincia', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('referencias', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ciudad', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cp_usuario', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('localidad', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
