"""initial tables

Revision ID: cb1f37de4b21
Revises: 
Create Date: 2025-09-23 16:35:42.668779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1f37de4b21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('galeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email_contacto', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('cp_usuario', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('referencias', sa.String(length=300), nullable=True),
    sa.Column('tipo_envio', sa.String(length=50), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('es_viejo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña_hash', sa.String(length=255), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('vendido', sa.Boolean(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_imagenes')
    op.drop_table('pedido_items')
    op.drop_table('productos')
    op.drop_table('usuarios')
    op.drop_table('pedidos')
    op.drop_table('galeria')
    op.drop_table('categorias')
    op.drop_table('banners')
    # ### end Alembic commands ###
